name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: build / ${{ matrix.os }} / zig ${{ matrix.zig-version }}

    strategy:
      fail-fast: false
      matrix:
        zig-version: ["0.12.0", "0.12.1", "0.13.0"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}

      - name: Build
        run: zig build ${{ matrix.options }} --release=fast --summary all
